sudo: required
services: docker
language: bash

before_install:
  - apt-get update && apt-get install -y qemu-user-static binfmt-support
  - docker pull multiarch/qemu-user-static:register
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    
script:
  - docker run --rm -t arm32v6/alpine uname -a
  - cd zerotier && make all 
