sudo: required
services: docker
language: bash

before_install:
  - docker pull multiarch/qemu-user-static:register
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    
script:
  - docker run --rm -t multiarch/ubuntu-debootstrap:armhf-bionic uname -a
  - cd zerotier && make all 
